version: '3.0'
services:

#  http-proxy:
#    container_name: http-proxy
#    image: nginx:alpine
#    volumes:
##      - type: bind
##        source: ./conf.d
##        target: /etc/nginx/conf.d
#       - "./http-conf.d:/etc/nginx/conf.d"
#       - "./stream-conf.d:/etc/nginx/stream-conf.d"
#       - "./nginx.conf:/etc/nginx/nginx.conf"
#    ports:
#     - "80:80"
##    environment:
##     - NGINX_HOST=micro-red.ucuenca.edu.ec
##     - NGINX_PORT=80

#   mqtt-proxy:
#     container_name: mqtt-proxy
#     image: nginx:alpine
#     volumes:
# #      - type: bind
# #        source: ./conf.d
# #        target: /etc/nginx/conf.d
#        - "./mqtt-conf.d:/etc/nginx/conf.d"
#     ports:
#      - "1883:80"
# #    environment:
# #     - NGINX_HOST=micro-red.ucuenca.edu.ec
# #     - NGINX_PORT=80


  zookeeper:
    container_name: zookeeper
    restart: always
    image: "zookeeper:3.5"
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
  kafka:
    container_name: kafka
    restart: always
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  microgridtb:
    container_name: microgridtb
    restart: always
    image: "thingsboard/tb-postgres"
    depends_on:
      - kafka
    ports:
    # connect local port 8080 to exposed internal HTTP port 9090
      - "80:9090"
    # connect local port 1883 to exposed internal MQTT port 1883
      - "1883:1883"
    # connect local port 7070 to exposed internal Edge RPC port 7070
      - "7070:7070"
    # connect local UDP ports 5683-5688 to exposed internal COAP and LwM2M ports
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
    volumes:
      - ~/.microgridtb-data:/data
      - ~/.microgridtb-logs:/var/log/thingsboard
#    command: sh -c "echo \"---------------------------- `id`\""
